FROM ros:humble
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && usermod -aG video ${USERNAME} 
    
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3-pip
RUN pip install --no-cache-dir --upgrade setuptools==58.2.0
RUN pip install --no-cache-dir --upgrade opencv-python
RUN pip install --no-cache-dir --upgrade tensorflow==2.12.0
RUN pip install --no-cache-dir --upgrade torch
RUN pip install --no-cache-dir --upgrade torchvision
RUN pip install --no-cache-dir --upgrade tqdm
RUN pip install --no-cache-dir --upgrade Pillow
RUN pip install --no-cache-dir --upgrade tensorrt
RUN pip install --no-cache-dir --upgrade easydict
RUN pip install --upgrade ultralytics
RUN pip install shapely
ENV SHELL /bin/bash
RUN echo "export DISPLAY=unix:0" >> /etc/bash.bashrc


# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME


CMD ["/bin/bash"]